# Generated by Django 4.0.3 on 2022-03-24 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(max_length=100, unique=True)),
                ('name', models.CharField(max_length=50)),
                ('complete', models.BooleanField(default=False)),
            ],
        ),
    ]
