# Generated by Django 4.0.3 on 2022-03-24 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fileStore', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(max_length=100, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(blank=True, max_length=1000, null=True)),
                ('active', models.BooleanField(default=False)),
            ],
        ),
    ]
